namespace EasMe
{
    public enum LogType
    {
        BASE = 0,
        EXCEPTION = 1,
        WEB = 2,
        
    }

    public enum Severity
    {
        BASE = 100,
        INFO = 101,
        WARN = 102,
        ERROR = 103,
        DEBUG = 104,
        EXCEPTION = 105,
        FATAL = 106
    }
    public enum Error
    {
        SUCCESS = 100,
        INFO = 101,
        WARN = 102,
        ERROR = 103,
        DEBUG = 104,
        EXCEPTION = 105,
        FATAL = 106,        
        FAILED = 107,
        TIMEOUT = 108,
        SERVICE = 109,
        
        SQL_ERROR = 200,
        SQL_UPDATE_FAILED = 201,
        SQL_INSERT_FAILED = 202,
        SQL_DELETE_FAILED = 203,
        SQL_CREATE_FAILED = 204,
        SQL_TRUNCATE_FAILED = 205,
        SQL_GET_TABLE_FAILED = 206,
        SQL_EXEC_NONQUERY_FAILED = 207,
        SQL_EXEC_SCALAR_FAILED = 208,
        SQL_BACKUP_DATABASE_FAILED = 209,
        SQL_SHRINK_DATABASE_FAILED = 210,
        SQL_DROP_DATABASE_FAILED = 211,
        SQL_DROP_TABLE_FAILED = 212,
        SQL_RESTORE_DATABASE_FAILED = 213,
        SQL_CREATE_DATABASE_FAILED = 214,
        SQL_NO_PERMISSION = 215,
        SQL_NO_ROWS_FOUND = 216,
        SQL_NO_ROWS_AFFECTED = 217,
        SQL_NO_TABLE_FOUND = 218,

        LOGGING_ERROR = 300,
        SERIALIZATION_ERROR = 301,
        DESERIALIZATION_ERROR = 302,        
        FAILED_TO_CREATE = 303,
        FAILED_TO_DELETE = 304,
        FAILED_TO_READ = 305,
        FAILED_TO_WRITE = 306,
        FAILED_TO_CONVERT = 307,
        FAILED_TO_MOVE = 308,
        FAILED_TO_PARSE = 309,
        TOO_BIG_VALUE = 310,
        TOO_SMALL_VALUE = 311,
        SAME_VALUE = 312,
        FAILED_TO_COPY = 312,
        FAILED_TO_CUT = 312,
        FAILED_TO_PASTE = 312,

        NOT_EXISTS = 400,
        NOT_FOUND = 401,
        NOT_ALLOWED = 402,
        NOT_SUPPORTED = 403,
        NOT_AVAILABLE = 404,
        NOT_ENABLED = 405,
        NOT_DISABLED = 406,
        NOT_CONNECTED = 407,
        NOT_LOGGED_IN = 408,
        NOT_LOGGED_OUT = 409,
        NOT_AUTHORIZED = 410,
        NOT_AUTHENTICATED = 411,
        NOT_READY = 412,
        NOT_INITIALIZED = 413,
        ALREADY_EXISTS = 414,
        ALREADY_USED = 415,
        ALREADY_IN_USE = 416,
        EXPIRED = 417,
        NOT_EXPIRED = 418,
        IS_BEING_USED = 419,
        NOT_LOADED = 420,
        NOT_POSSIBLE = 421,
        NOT_VALID = 422,
        NULL_REFERENCE = 423,

        AUTHENTICATION_FAILED = 500,
        AUTHORIZATION_FAILED = 501,
        TOKEN_INVALID = 502,
        PASSWORD_INCORRECT = 503,
        USERNAME_INCORRECT = 504,
        EMAIL_INCORRECT = 505,
        EMAIL_ALREADY_SENT = 506,
        EMAIL_SENT_FAILED = 507,
        NO_ONLINE_NETWORK = 508,
        FAILED_TO_CONNECT = 509,
        FAILED_TO_SEND_GET = 510,
        FAILED_TO_VALIDATE = 511,
        FAILED_TO_SEND_POST = 513,
        FAILED_TO_SEND_DELETE = 514,
        FAILED_TO_SEND_PATCH = 515,
        FAILED_TO_SEND_PUT = 516,
        FAILED_TO_SEND_REQUEST = 517,


    }
    public enum LogNo
    {
        ErrINFO = 0,
        ErrWARN = 1,
        ErrERROR = 2,
        ErrDEBUG = 3,
        ErrEXCEPTION = 4,
        ErrFATAL = 5,
        ErrSUCCESS = 6,
        ErrFAILED = 7,
        ErrSERVICE = 9,
        ErrSQL = 10,
        ErrEASLOG = 11,
        ErrSERIALIZATION = 12,
        ErrDESERIALIZATION = 13,
        ErrEASAPI = 14,
        ErrEASDEL = 15,
        ErrEASEXT = 16,
        ErrEASGENERATE = 17,
        ErrEASHASH = 18,
        ErrEASINI = 19,
        ErrEASJWT = 20,
        ErrEASLOGREAD = 21,
        ErrEASMAIL = 22,
        ErrEASPROXY = 23,
        ErrEASQL = 24,
        ErrEASRECAPTCHA = 25,
        ErrEASSYSTEM = 26,
        ErrEASVALIDATE = 27,
    }
}
